// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Refoundd.Models;

#nullable disable

namespace Refoundd.Migrations
{
    [DbContext(typeof(RefoundContext))]
    partial class RefoundContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Refoundd.Models.Item", b =>
                {
                    b.Property<int>("Item_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Item_Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Item_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Item_Id = 1,
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Leather wallet with cards",
                            Item_Name = "Black Wallet",
                            Location = "University",
                            Status = "Lost",
                            User_Id = 1
                        },
                        new
                        {
                            Item_Id = 2,
                            Date = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Black Samsung mobile",
                            Item_Name = "Samsung Phone",
                            Location = "Library",
                            Status = "Found",
                            User_Id = 2
                        },
                        new
                        {
                            Item_Id = 3,
                            Date = new DateTime(2023, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stainless steel bottle with a silver cap and a 'Go Bears' sticker.",
                            Item_Name = "Blue HydroFlask",
                            Location = "Central Library, Level 2",
                            Status = "Found",
                            User_Id = 1
                        },
                        new
                        {
                            Item_Id = 4,
                            Date = new DateTime(2023, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Left in a black sleeve. Has a small scratch on the front logo.",
                            Item_Name = "Silver MacBook Air",
                            Location = "Science Building, Room 402",
                            Status = "Lost",
                            User_Id = 1
                        },
                        new
                        {
                            Item_Id = 5,
                            Date = new DateTime(2023, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Toyota key fob with several house keys and a gym membership card.",
                            Item_Name = "Keys with Red Lanyard",
                            Location = "Student Union, Food Court",
                            Status = "Found",
                            User_Id = 1
                        },
                        new
                        {
                            Item_Id = 6,
                            Date = new DateTime(2023, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bi-fold wallet containing student ID and transit card. Reward offered.",
                            Item_Name = "Black Leather Wallet",
                            Location = "Gym, Locker Rooms",
                            Status = "Lost",
                            User_Id = 1
                        },
                        new
                        {
                            Item_Id = 7,
                            Date = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tortoise shell frames found near the window seating area.",
                            Item_Name = "Reading Glasses",
                            Location = "University Cafe",
                            Status = "Found",
                            User_Id = 1
                        },
                        new
                        {
                            Item_Id = 8,
                            Date = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Texas Instruments TI-84 Plus, name 'Alex' on the back.",
                            Item_Name = "Scientific Calculator",
                            Location = "Lecture Hall A",
                            Status = "Lost",
                            User_Id = 1
                        },
                        new
                        {
                            Item_Id = 9,
                            Date = new DateTime(2023, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dark blue foldable umbrella found in the umbrella stand.",
                            Item_Name = "Umbrella",
                            Location = "Main Entrance Lobby",
                            Status = "Found",
                            User_Id = 1
                        },
                        new
                        {
                            Item_Id = 10,
                            Date = new DateTime(2023, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Card for student #202495. Lost near the shuttle terminal.",
                            Item_Name = "Student ID Card",
                            Location = "West Campus Bus Stop",
                            Status = "Lost",
                            User_Id = 1
                        });
                });

            modelBuilder.Entity("Refoundd.Models.User", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Flag")
                        .HasColumnType("int");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            User_Id = 1,
                            Email = "ali@example.com",
                            First_Name = "Ali",
                            Flag = 0,
                            Last_Name = "Ahmed",
                            Password = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
                            User_Name = "Ali"
                        },
                        new
                        {
                            User_Id = 2,
                            Email = "sara@example.com",
                            First_Name = "Sara",
                            Flag = 0,
                            Last_Name = "Khan",
                            Password = "d404559f602eab6fd602ac7680dacbfaadd13630335e951f097af3900e9de176",
                            User_Name = "Sara"
                        },
                        new
                        {
                            User_Id = 3,
                            Email = "test@university.edu",
                            First_Name = "Test",
                            Flag = 0,
                            Last_Name = "User",
                            Password = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
                            User_Name = "test_user"
                        });
                });

            modelBuilder.Entity("Refoundd.Models.Item", b =>
                {
                    b.HasOne("Refoundd.Models.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Refoundd.Models.User", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
